work_dir: ./work_dir/recognition/iMiGUE/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/iMiGUE/imigue_processed/train_data.npy
  label_path: ./data/iMiGUE/imigue_processed/train_label.pkl
test_feeder_args:
  data_path: ./data/iMiGUE/imigue_processed/valid_data.npy
  label_path: ./data/iMiGUE/imigue_processed/valid_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 32
  dropout: 0.1
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose22'
    strategy: 'spatial'

#optim
weight_decay: 0.00001
base_lr: 0.0001
step: [4, 6]

# training
device: [0]
batch_size: 32
test_batch_size: 64
num_epoch: 8



