weights: ./work_dir/recognition/mg/ST_GCN/epoch10_model.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/SMGskeletonB/test_data.npy
  label_path: ./data/SMGskeleton/test_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 17
  dropout: 0.1
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 64

