work_dir: ./work_dir/recognition/smg/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/SMGskeleton/train_data.npy
  label_path: ./data/SMGskeleton/train_label.pkl
test_feeder_args:
  data_path: ./data/SMGskeleton/test_data.npy
  label_path: ./data/SMGskeleton/test_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 17
  dropout: 0.1
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.01
step: [5, 10]

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 20



