# command line: main.py recognition -c config/st_gcn/imigue/train.yaml

base_lr: 0.0001
batch_size: 32
config: config/st_gcn/imigue/train.yaml
debug: false
device:
- 0
eval_interval: 1
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
model: net.st_gcn.Model
model_args:
    dropout: 0.1
    edge_importance_weighting: true
    graph_args:
        layout: openpose22
        strategy: spatial
    in_channels: 3
    num_class: 32
nesterov: true
num_epoch: 8
num_worker: 4
optimizer: SGD
pavi_log: false
phase: train
print_log: true
save_interval: 10
save_log: true
save_result: true
show_topk:
- 1
- 5
start_epoch: 0
step:
- 4
- 6
test_batch_size: 64
test_feeder_args:
    data_path: ./data/iMiGUE/imigue_processed/valid_data.npy
    label_path: ./data/iMiGUE/imigue_processed/valid_label.pkl
train_feeder_args:
    data_path: ./data/iMiGUE/imigue_processed/train_data.npy
    label_path: ./data/iMiGUE/imigue_processed/train_label.pkl
use_gpu: true
weight_decay: 1.0e-05
weights: null
work_dir: ./work_dir/recognition/iMiGUE/ST_GCN
